<?xml version="1.0" ?>
<!DOCTYPE MAIL [
	<!ELEMENT MAIL (HEADER, BODY)>
	<!ELEMENT HEADER (RECEIVER, SENDER, TITLE)>
	<!ELEMENT RECEIVER (#PCDATA)>
	<!ELEMENT SENDER (#PCDATA)>
	<!ELEMENT TITLE (#PCDATA)>
	<!ELEMENT BODY (#PCDATA)>
]>
<!-- TODO: 위 DTD를 참조하여 MAIL element를 생성하시오. -->
<MAIL>
	<HEADER>
		<RECEIVER>받는 사람</RECEIVER>
		<SENDER>보내는 사람</SENDER>
		<TITLE>제목</TITLE>
	</HEADER>
	<BODY>내용</BODY>
</MAIL>
<!-- END: -->